### ISSUE TITLE
.gitignore includes publish profiles

### ISSUE THREAD

**Issue by MarkSFrancis** [Lucisano/blazor-components#1]
The gitignore seems to mistakenly include the [publish profile folder](https://github.com/Lucisano/blazor-components/tree/master/BlazorComponents/Properties/PublishProfiles). You could either add this path to the .gitignore file, or just swap out the .gitignore entirely for a [standard Visual Studio one](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore).

After updating the .gitignore, you'll need to remove the files from the repository. See [here](https://stackoverflow.com/a/34435207/5952236) for a guide on this

**Comment by Lucisano** [comment]
whoops. sorted
